name: Auto Translate Markdown Files

on:
  push:
    branches:
      - main

jobs:
  auto_translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run auto translator
      run: python auto-translater.py ${{ secrets.CHATGPT_API_BASE }} ${{ secrets.CHATGPT_API_KEY }} 

    - name: 设置 Git 配置
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 提交新的博客文章
        run: |
          git add source/_posts/*
          git commit -m "Add new posts via GitHub Actions" || echo "No new posts to commit."
          git push origin main
